### ISSUE TITLE
Redirect after delete

### ISSUE THREAD

**Issue by janboddez** [janboddez/fstop#21]
So after using the Delete button on an Edit "Entry" screen, at least using Vivaldi, I don't get redirected to the `entries.index` view and instead see a 404.

I'm guessing Vivaldi doesn't set a referrer header or something, and the following returns false:
```
session()->previousUrl() === route('admin.entries.edit', $entry)
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the destroy method in EntryController to handle cases where the referrer might not be set correctly, ensuring proper redirection after deleting an entry.

You can review changes in this commit: https://github.com/mnmnk43434/janboddez-fstop-21/commit/c886da3783be6abe8873bb7bf6e8483e5849faf9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by janboddez** [comment]
The session URL is somehow wrong! In this browser!

But we could use `app('redirect')->getUrlGenerator()->previous()`, which first looks at any referrer URL. The outcome of that function is where `back()` would take us, and we're trying to prevent it from taking us to the entry we just deleted, so comparing to that URL should be "safe."
